### ISSUE TITLE
To-Do v0.2

### ISSUE THREAD

**Issue by adityaarun1** [adityaarun1/faster_rcnn_pytorch#1]
- [x] Ensure python3 compatibility
- [x] Fix Tensorboard integration (Crayon does not work for me! ).
- [x] Create separate train and validation split. Currently it uses entire train-val of voc07 for training.
- [x] Improve the baseline (from 66.1% mAP to 69.9% mAP).
- [x] Create separate branch for Fast RCNN. Ensure it works with Selective Search, MCG and Edge Boxes proposals.
- [ ] Remove OpenCV display option, integrate them with Tensorboard/Visdom.

**Comment by adityaarun1** [comment]
The current best performing baseline gives 68.2% mAP. This still needs further improvement.

**Comment by adityaarun1** [comment]
Tensorboard support is removed. Added Visdom support for visualization of graphs.
